[package]
name = "dice-roller-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
readonly = "0.2"
slint = "0.3.5"

[build-dependencies]
slint-build = "0.3.5"
